# This is a basic workflow to help you get started with Actions

name: Workflow to trigger the playbook with --check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ansible:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        name: ${{ secrets.USER_NAME }}
        

    
    - name: Run playbook with --check --diff
      working-directory: ansible
      run: |
        chmod 666 .vault_password_file
        echo "$VAULT_PASSWORD" > .vault_password_file      
        ansible-inventory --graph
        ansible-playbook wordpress-install.yml --check --diff
      env:
        ANSIBLE_CONFIG: ansible.cfg
        VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD_FILE }}  
